[package]
name = "bleak-blocks"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
macroquad = "0.4.14"
ordered-float = "5.0.0"
palette = "0.7.6"
strum = { version = "0.27.2", features = ["derive"] }
